--- #YAML:1.0
name:               XML-Bare
version:            0.52
abstract:           A minimal XML parser / schema checker / pretty-printer using C internally.
author:
    - David Helkowski <cpan@codechild.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.30
build_requires:
    Data::Dumper:   0
    English:        0
    File::Find:     0
    File::Temp:     0
    Scalar::Util:   0
    Test::Harness:  0
    Test::More:     0.94
requires:
    Carp:        0
    DynaLoader:  0
    Exporter:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
